Opcja A — Native SailPoint JDBC Connector (rekomendowana)
Strona SailPoint
Pierwszym krokiem jest wejście do każdej aplikacji JDBC która aktualnie znajduje się w trybie maintenance i zmiana jej statusu na aktywny. Przed reaktywacją należy zweryfikować czy dane konfiguracyjne połączenia (host, port, nazwa bazy) są nadal aktualne — w okresie uśpienia instancji mogły nastąpić zmiany infrastrukturalne.
Następnie w ustawieniach aplikacji należy skonfigurować sterownik JDBC właściwy dla danego silnika bazodanowego, uzupełnić connection URL, nazwę service account oraz hasło. Po poprawnym ustawieniu połączenia należy użyć funkcji Test Connection aby potwierdzić że SailPoint Virtual Appliance ma dostęp sieciowy do serwera bazodanowego.
Kolejnym krokiem jest konfiguracja zapytania SQL dla agregacji kont. Zapytanie musi zwracać unikalny identyfikator konta, nazwę wyświetlaną, status aktywności oraz datę utworzenia — pobierając dane ze słowników systemowych danego silnika bazodanowego.
Kluczowym elementem — którego brakowało w podejściu CSV — jest osobne zapytanie SQL dla agregacji uprawnień. Zapytanie to musi zwracać powiązanie konta z jego uprawnieniami na poziomie obiektów bazodanowych, czyli roles, grants oraz permissions przypisane do każdego konta. Dopiero to zapytanie sprawia że recenzent podczas recertyfikacji widzi nie tylko samo konto lecz również co to konto może wykonywać w bazie danych.
W zakładce Schema należy zmapować zwrócone kolumny SQL na atrybuty SailPoint — osobno dla typu Account oraz osobno dla typu Entitlement. Bez poprawnego schematu SailPoint nie będzie wiedział które pole jest identyfikatorem konta a które nazwą uprawnienia.
Następnie należy skonfigurować regułę korelacji która łączy konto bazodanowe z tożsamością w SailPoint Identity Cube. Reguła powinna dopasowywać nazwę konta do atrybutu pracownika takiego jak identyfikator pracownika lub prefiks adresu email.
Na końcu należy ustawić harmonogram automatycznej agregacji — agregacja kont i uprawnień powinna uruchamiać się co 24 godziny, natomiast delta aggregation wykrywająca przyrostowe zmiany może być uruchamiana co kilka godzin w zależności od wymagań organizacji.
Strona bazy danych
Na każdym serwerze bazodanowym należy utworzyć dedykowany service account wyłącznie na potrzeby SailPoint. Konto to musi działać zgodnie z zasadą least privilege — posiada wyłącznie uprawnienia do odczytu słowników systemowych bazy danych, bez możliwości modyfikacji danych ani struktury bazy.
Konkretnie konto musi mieć uprawnienie do wykonywania zapytań SELECT na widokach i tabelach systemowych które przechowują informacje o użytkownikach, rolach oraz przypisanych uprawnieniach. Dla każdego silnika bazodanowego są to inne obiekty systemowe — na przykład w Oracle są to widoki takie jak dba_users, dba_sys_privs, dba_tab_privs i dba_role_privs, w SQL Server są to widoki sys.server_principals oraz sys.database_permissions, w PostgreSQL są to tabele katalogu pg_catalog oraz widoki information_schema, w IBM DB2 są to tabele SYSCAT, natomiast w MongoDB wymagana jest rola clusterMonitor oraz readAnyDatabase na poziomie bazy administracyjnej.
Poza uprawnieniami na poziomie bazy danych konieczne jest otwarcie reguły firewall która pozwala Virtual Appliance SailPoint na nawiązanie połączenia TCP z każdym serwerem bazodanowym na właściwym porcie silnika. Bez tej reguły test połączenia w SailPoint zakończy się timeoutem niezależnie od poprawności konfiguracji konektora.
Ostatnim krokiem po stronie infrastruktury jest umieszczenie pliku JAR ze sterownikiem JDBC właściwym dla danego silnika w katalogu konektora na serwerze SailPoint lub Virtual Appliance — bez tego pliku SailPoint nie jest w stanie załadować klasy sterownika i nawiązać połączenia.

Opcja B — Web Services Connector
Opcja ta ma zastosowanie wyłącznie jeśli serwer bazodanowy wystawia REST API które zwraca dane o kontach i uprawnieniach — po stronie SailPoint należy skonfigurować Web Services Connector definiując endpointy, metodę uwierzytelniania oraz mapowanie odpowiedzi JSON na atrybuty kont i uprawnień, natomiast po stronie bazy danych konieczne jest zbudowanie lub udostępnienie takiego API które obsługuje zapytania o użytkowników i ich uprawnienia, co w przypadku standardowych silników relacyjnych wymaga dodatkowej warstwy aplikacyjnej i jest rzadko stosowane.

Opcja C — Script Connector (PowerShell)
Po stronie SailPoint należy skonfigurować Script Connector wskazując skrypt który generuje plik CSV zawierający konta wraz z kolumnami uprawnień, a następnie ustawić harmonogram jego importu jako źródła danych dla aplikacji, natomiast po stronie bazy danych lub serwera pośredniczącego należy napisać i wdrożyć skrypt PowerShell lub inny skrypt powłoki który łączy się z silnikiem bazodanowym, odpytuje słowniki systemowe o konta i uprawnienia, a wynik zapisuje w pliku CSV w lokalizacji dostępnej dla SailPoint — jest to rozwiązanie prostsze we wdrożeniu lecz trudniejsze w utrzymaniu i podatne na błędy przy zmianach schematu zapytań.